modLoader="javafml"
loaderVersion="[45,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/Guidebook/issues"

[[mods]]
modId="gbook"
version="${file.jarVersion}"
displayName="Guidebook"
description='''
Books that guide
'''
updateJSONURL="https://raw.githubusercontent.com/gigaherz/Guidebook/master/update.json"
displayURL="https://github.com/gigaherz/Guidebook"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.gbook]]
    modId="forge"
    mandatory=true
    versionRange="[45.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gbook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"