modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/Guidebook/issues"

[[mods]]
modId="gbook"
version="${file.jarVersion}"
displayName="Guidebook"
description='''
Books that guide
'''
updateJSONURL="https://raw.githubusercontent.com/gigaherz/Guidebook/master/update.json"
displayURL="https://github.com/gigaherz/Guidebook"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.gbook]]
    modId="neoforge"
    type="required"
    versionRange="[20.5.0-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gbook]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.5,1.21)"
    ordering="NONE"
    side="BOTH"